### ISSUE TITLE
Test TestBiuteeUsage.runFullBiutee() fails

### ISSUE THREAD

**Issue by oferbr** [hltfbk/Excitement-Open-Platform#254]
Currently it fails over something in the configuration, and in general may fail due to to the addition of the ETE classes (not all code was updated accordingly).
Make sure to run the test from the workdir of the latest biutee_env!

**Comment by rzanoli** [comment]
I think this issue should have already been solved.

**Comment by oferbr** [comment]
@rzanoli I am already not involved, but as I got a notification for this, I didn't understand whether the issue was actually resolved and now the test runs-error free, or just that it "should have been resolved". I think the guys at BIU still want BIUTEE to be able to run from the EOP, so if this siple test cannot be run, maybe they would want to fix it.
