### ISSUE TITLE
Missing archive link in mailing list

### ISSUE THREAD

**Issue by gilnoh** [hltfbk/Excitement-Open-Platform#272]
The mailing list only introduces how to register to the mailing list, but it does not shows the link to "Google Group", and read archived text. (no archive link there.) 
http://hltfbk.github.io/Excitement-Open-Platform/mail-lists.html

Ideally, this link should be filled to Google Group, and users should be able to read previous discussions without joining the mailing list.

**Comment by rzanoli** [comment]
I've just added the links in the Mailing list wiki page so that users can read the  discussion without joining the mailing lists.
