### ISSUE TITLE
Unsufficient instruction for using different configuration files of TIE using TreeTagger

### ISSUE THREAD

**Issue by an-fbk** [hltfbk/Excitement-Open-Platform#366]
Hi everybody,

I tried the EOP 1.1.1 (latest version) and followed the step-by-step instructions. When I tried TIE EDA with the configuration file "MaxEntClassificationEDA_Base+VO+TP+TPPos+TS_EN", I got the error:

org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl callAnalysisComponentProcess(407)
SEVERE: Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at de.tudarmstadt.ukp.dkpro.core.treetagger.TreeTaggerPosLemmaTT4J.process(TreeTaggerPosLemmaTT4J.java:206)

This is an error due to using "MaltParserEN" pipeline with missing TreeTagger. However, there is no information indicating this error explicitly so that an end-user can understand and get a solution for it. I suggest we should give more info about which pipeline needs to use which external tools/resources (i.e. a dependency diagram)

**Comment by rzanoli** [comment]
In the TIE's configuration files I've just added the information that MaltParser uses TreeTagger and so TreeTagger has to be already installed.
