### ISSUE TITLE
(Documentation error) BIUTEE installation description is wrong. 

### ISSUE THREAD

**Issue by gilnoh** [hltfbk/Excitement-Open-Platform#481]
A user reported the folloing error on BIUTEE installation description. 
https://github.com/hltfbk/EOP-1.1.4/wiki/Installing-BIUTEE

BIUTEE installation description describes a directory name of 
``$EOP/target/EOP-{_version_}/eop-resources-{_version_}/BIUTEE_Environment/``

I guess that this might be a failure of automatic generation...  (or was this intentional?) 
Note that in 1.1.3 documentation, _version_ parts are successfully converted to actual version number even in the Wiki documentations. 

(original posting related this issue on EOP user list) 
https://groups.google.com/forum/?hl=en#!topic/eop-users/69c3DYnb9vE

**Comment by rzanoli** [comment]
I think that this issue can be closed.
