### ISSUE TITLE
Wrong result file for the  single hypothesis pair example in the quick start guide 

### ISSUE THREAD

**Issue by bakfire07** [hltfbk/Excitement-Open-Platform#504]
For annotating a single hypothesis pair - The results get saved into ./eop-resources-1.2.0/results/result.xml and not EditDistanceEDA_EN.xml_results.xml as mentioned in quick start

**Comment by rzanoli** [comment]
EOPRunner saves the results in a file namely results.xml when a single T/H pair is provided from the command line, in a file XXXEDA_results.xml when the T/H pairs are from a file. We've just updated the QuickStart of EOP 1.2.0 whereas for the next EOP release they are thinking to adopt the same policy for the 2 cases above: the results for both the cases will be saved in XXXEDA_results.xml
