### ISSUE TITLE
problem installing EOP

### ISSUE THREAD

**Issue by diziup** [hltfbk/Excitement-Open-Platform#522]
I am facing a problem trying to install the new version of EOP on a linux machine,
using the command  sh ./install.sh 1.2.1 treetagger:
When it gets to the point of checking the awk, it seems to crash, after if finished to check ant, maven etc.
(The command without the treegager works and all is installed) 
see please the following image,
![1](https://cloud.githubusercontent.com/assets/8167037/6776150/afbf2372-d143-11e4-9500-b1765c3ccbea.png).

I also tried to install it using the instructions here via CLI (https://github.com/hltfbk/EOP-1.2.1/wiki/Step%20by%20Step,%20TreeTagger%20Installation) 
and get this err
![2](https://cloud.githubusercontent.com/assets/8167037/6776155/bf0a86f0-d143-11e4-83a3-9913d7235b25.png)
or (see please 2. png).

Is there any idea what could be the problem and solution?

Much thanks in advance,
Liora Braunstein

**Comment by rzanoli** [comment]
As regards the first issue, open the install.sh script with your favorite text editor and look for the section: ant and awk test; then add the "--usage" oprion to the awk command, i.e. awk --usage; rerun the script.

Concerning the second issue, could you tell us which version of ant are you using?

Best,
Roberto

**Comment by diziup** [comment]
Thank you for the reply,
The --sage addition fixed it,
yet now I get the same error as in the second issue :
[image: Inline image 1]

The ant version I am using is:
Apache Ant version 1.7.1 compiled on August 24 2010

Thanks again,
Liora

**Comment by rzanoli** [comment]
using a more recent version of ant, e.g., apache-ant-1.9.4 should solve the issue

**Comment by diziup** [comment]
Yes, that indeed resolved that.
One more issue though unfortunately -

[image: Inline image 1]
And indeed in the build.xml file I see that url
http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/english-par-linux-3.2.bin.gz
is empty...

Thanks again,
Liora

**Comment by rzanoli** [comment]
we have just updated the build.xml file, Download it again and let we know.

**Comment by rzanoli** [comment]
Liora, could you tell us if you were able to install the EOP so that we can close this issue?

**Comment by diziup** [comment]
Yes,
I installed EOP,

Thank you,
Liora

**Comment by rzanoli** [comment]
The issue has been solved so that we can close it.
