### ISSUE TITLE
Issue with install file

### ISSUE THREAD

**Issue by ankitar** [hltfbk/Excitement-Open-Platform#525]
I am trying to install EOP following the link (https://github.com/hltfbk/Excitement-Open-Platform/wiki/Installation). The install.sh file seems to have some problem. I am getting the following error:
./install.sh: 30: ./install.sh: Syntax error: "(" unexpected. I searched the error but none of the solutions helped.

System Config: 
Ubuntu 14.04
Memory - 8 GB
Processor - i7 - 2600 CPU @ 3.40 GHZ * 8
OS Type - 64 bit
Disk Space - 79.6 GB

**Comment by rzanoli** [comment]
It seems that you are working with the code and documentation of the next EOP release (that which is under developing). I think you should instead use the last EOP release (i.e., 1.2.1) which is available at this address: http://hltfbk.github.io/Excitement-Open-Platform/

Let us know if it work for you.

Best,
Roberto

**Comment by ankitar** [comment]
Thanks Robert. I will try this.

**Comment by ankitar** [comment]
I also tried the V 1.2.0 but getting the same error.

**Comment by rzanoli** [comment]
could you send us the command you use for installing the EOP and its output?

**Comment by ankitar** [comment]
I followed the steps of Java Distribution from the link below : 
https://github.com/hltfbk/EOP-1.2.0/wiki/Installation
I used 'sh ./install.sh 1.2.0' command and the error I am getting is './install.sh: 30: ./install.sh: Syntax error: "(" unexpected'

**Comment by rzanoli** [comment]
try to run the install script without sh, i.e.,  ./install.sh 1.2.0

Then, are you sure you want to use EOP 1.2.0 instead of EOP 1.2.1?

**Comment by rzanoli** [comment]
or:  bash  ./install.sh 1.2.0

**Comment by ankitar** [comment]
I tried with both EOP 1.2.0 and 1.2.1 same error.

**Comment by rzanoli** [comment]
so, also when you run either the command  ./install.sh 1.2.0, or  bash ./install.sh 1.2.0, it doesn't work. Is it right?

**Comment by ankitar** [comment]
./install.sh 1.2.0 is working. Please change the documentation(https://github.com/hltfbk/EOP-1.2.0/wiki/Installation), it says run sh ./install.sh 1.2.0 .

**Comment by rzanoli** [comment]
It has just been updated. Thanks for warning us.
