### ISSUE TITLE
Installation of EOP 1.2.3 Error!

### ISSUE THREAD

**Issue by sphinx3** [hltfbk/Excitement-Open-Platform#538]
Hi!
         I downloaded according to the Installation page and followed the steps and when I reached the install part, got this error:

> bash ./install.sh 1.2.3

Testing Maven ...  
./install.sh: line 47: mvn: command not found
Error!

In my directory, there is 
eop-resources-1.2.3.tar.gz
Excitement-Open-Platform-1.2.3.tar.gz
install.sh
build.xml

Can anyone please help?  Thank you very much :)

**Comment by qwaider** [comment]
You have to install maven to your system.
https://maven.apache.org/install.html

**Comment by sphinx3** [comment]
Thanks!  :) 

    On Thursday, August 18, 2016 9:02 PM, qwaider <notifications@github.com> wrote:
 

 You have to install maven to your system.
https://maven.apache.org/install.html—
