### ISSUE TITLE
NoClassDefFoundError error message

### ISSUE THREAD

**Issue by vaskonov** [hltfbk/Excitement-Open-Platform#545]
Hello,

I am trying to run examples from Quick Start, however it seems like the definition of CLASSPATH is lack.
How should I define  the CLASSPATH environment variable. 

Currently, I am stuck with the following error message
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: eu/excitementproject/eop/alignmentedas/p1eda/visualization/Visualizer

```

I appreciate you help.

**Comment by rzanoli** [comment]
Hello,
could you tell us the steps you did to install the EOP? And also if you are using the EOP from Eclipse or from the command line? Which operative system you use is another information that could help us. Finally you should report the step in the quick start that produces that error and the steps that you were instead able to do without any errors.

**Comment by vaskonov** [comment]
Thank you for your quick response,

1) I installed the EOP by following the step from Installation-Users Distribution-Java Distribution.
2) I am using EOP from the command line.
3) OS: Linux Mint 17.2 Rafaela.
4) I tried to annotate the single pair by running the inserted below command, however, it failed with the error message.

```
java -Djava.ext.dirs=../EOP-1.2.3/ eu.excitementproject.eop.util.runner.EOPRunner -config ./eop-resources-1.2.3/configuration-files/EditDistanceEDA_EN.xml -test -text "Hubble is a telescope" -hypothesis "Hubble is an instrument" -output ./eop-resources-1.2.3/results/
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: eu/excitementproject/eop/alignmentedas/p1eda/visualization/Visualizer

```

**Comment by vaskonov** [comment]
The problem was solved by adding
$HOME_DIR/Excitement-Open-Platform-1.2.3/target/EOP-1.2.3/*
to 
CLASSPATH
